### ISSUE TITLE
New spot to set up OAuth for FB

### ISSUE THREAD

**Issue by AdamKing0126** [learn-co-students/devise_lab-v-000#105]
From the dashboard, at the bottom left, you see "Products" and just below that, "+ Add Product"

Click "Add Product" and choose "facebook login" - that's where you do your OAuth setup.

**Comment by tttra** [comment]
Please implement this change! I spent so much time digging, thinking that I was crazy not seeing it anywhere. Thank you so much!

**Comment by gj** [comment]
Fixed — thanks @AdamKing0126 !
